eliminate tabs.  use VERBOSE consistently.  use RETVAL consistently for script return, not just function returns.

diff --git a/util/init.d/weewx-multi b/util/init.d/weewx-multi
--- a/util/init.d/weewx-multi
+++ b/util/init.d/weewx-multi
@@ -107,24 +107,24 @@ do_stop() {
     fi
     start-stop-daemon --stop --user $WEEWX_USER --pidfile $PIDFILE
     # we cannot trust the return value from start-stop-daemon
-    RETVAL=2
+    RC=2
     c=0
-    while [ $c -lt 24 -a "$RETVAL" = "2" ]; do
+    while [ $c -lt 24 -a "$RC" = "2" ]; do
         c=`expr $c + 1`
         # process may not really have completed, so check it
         NPROC=$(count_procs $INSTANCE)
         if [ $NPROC = 0 ]; then
-            RETVAL=0
+            RC=0
         else
             echo -n "."
             sleep 5
         fi
     done
-    if [ "$RETVAL" = "0" -o "$RETVAL" = "1" ]; then
+    if [ "$RC" = "0" -o "$RC" = "1" ]; then
         # delete the pid file just in case
         rm -f $PIDFILE
     fi
-    return "$RETVAL"
+    return "$RC"
 }
 
 # send a SIGHUP to the daemon
@@ -164,27 +164,31 @@ if [ "$INSTANCES" = "" ]; then
     INSTANCES=$WEEWX_INSTANCES
 fi
 
+
+RETVAL=0
 case "$CMD" in
     start)
         for i in $INSTANCES; do
-	    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$i"
-	    do_start $i
-	    case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	    esac
+            [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$i"
+            do_start $i
+            case "$?" in
+                0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                1) [ "$VERBOSE" != no ] && log_action_cont_msg " already running" && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1; $RETVAL=1 ;;
+            esac
         done
-	;;
+        ;;
     stop)
         for i in $INSTANCES; do
-	    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$i"
-	    do_stop $i
-	    case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	    esac
+            [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$i"
+            do_stop $i
+            case "$?" in
+                0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                1) [ "$VERBOSE" != no ] && log_action_cont_msg " not running" && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1; $RETVAL=1 ;;
+            esac
         done
-	;;
+        ;;
     status)
         for i in $INSTANCES; do
             do_status "$i"
@@ -192,33 +196,35 @@ case "$CMD" in
         ;;
     reload|force-reload)
         for i in $INSTANCES; do
-	    log_daemon_msg "Reloading $DESC" "$i"
-	    do_reload $i
-	    log_end_msg $?
+            log_daemon_msg "Reloading $DESC" "$i"
+            do_reload $i
+            log_end_msg $?
         done
-	;;
+        ;;
     restart)
         for i in $INSTANCES; do
-	    log_daemon_msg "Restarting $DESC" "$i"
-	    do_stop $i
-	    case "$?" in
-	        0|1)
-		    do_start $i
-		    case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		    esac
-		    ;;
-	        *)
-	  	# Failed to stop
-		    log_end_msg 1
-		    ;;
-	    esac
+            [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$i"
+            do_stop $i
+            case "$?" in
+                0|1)
+                    do_start $i
+                    case "$?" in
+                        0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                        1) [ "$VERBOSE" != no ] && log_end_msg 1; RETVAL=1 ;; # Old process is still running
+                        *) [ "$VERBOSE" != no ] && log_end_msg 1; RETVAL=1 ;; # Failed to start
+                    esac
+                    ;;
+                *)
+                    [ "$VERBOSE" != no ] && log_end_msg 1
+                    RETVAL=1
+                    ;;
+            esac
         done
-	;;
+        ;;
     *)
-	echo "Usage: $0 {start|stop|restart|reload} [instance]" >&2
-	exit 3
-	;;
+        echo "Usage: $0 {start|stop|restart|reload} [instance]" >&2
+        exit 3
+        ;;
 esac
+
+exit $RETVAL
